# Generated by Django 3.0.4 on 2020-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='story',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogimages',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
